export const CURRENT_FACTORY_ADDRESS = '';

export const CURRENT_ACTON_TESTNET_FACTORY_ADDRESS = '';

export const CURRENT_MIGRATION_MARKET_CAP_NANO = '';

export const CURRENT_ACTON_TESTNET_MIGRATION_MARKET_CAP_NANO = '';
